# Dependencies
markdown:         redcarpet
highlighter:      pygments


# Setup
title:            Being Bayesian
tagline:          'A Jekyll theme'
description:      'The sun will come out Tomorrow'
url:              
baseurl:          

author:
  name:           'Park hyongsong'
  url:            

paginate:         5

