# Dependencies
markdown:         redcarpet
highlighter:      pygments


# Setup
title:            Being Bayesian
tagline:          'A Jekyll theme'
description:      'The sun will come out Tomorrow'
url:              https://hyongsong.github.io/
baseurl:          /

author:
  name:           'Park hyongsong'
  url:            https://hyongsong.github.io/

paginate:         5

# Custom vars
version:          
github:
  repo:           https://github.com/poole/hyde
